language: node_js
services:
  - docker

before_install:
  - base-image=qiugu/dep:2.0
  - music-image=qiugu/music:1.0
  - docker pull $base-image || true
  - docker pull $music-image || true
  - docker build -t music:1.0 --cache-from $base-image --cache-from $music-image .
  - docker push qiugu/dep:2.0
  - docker push qiugu/music:1.0
