name: Docker Image CI

on:
  push:
    branches: [ "final" ]
  pull_request:
    branches: [ "final" ]

jobs:
  build:
    name: Build base image and project image
    runs-on: ubuntu-latest
    env:
      BaseImage: qiugu/dep:2.0
      MusicImage: qiugu/music:1.0
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t $MusicImage --cache-from $BaseImage --cache-from $MusicImage .
  push:
    name: Log in to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: qiugu/music
      
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
