name: Docker Image CI

on:
  push:
    branches: [ "final" ]
  pull_request:
    branches: [ "final" ]
env:
  BaseImage: qiugu/dep:latest
  MusicImage: qiugu/music:latest

jobs:
  build:
    name: Log in and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker pull $BaseImage || true
          docker pull $MusicImage || true
          docker build -t $BaseImage --target dependency --cache-from $BaseImage --build-arg BUILDKIT_INLINE_CACHE=1 .
          docker build -t $MusicImage --cache-from $BaseImage --build-arg BUILDKIT_INLINE_CACHE=1 .
          # docker build -t $MusicImage .
          docker push $BaseImage
          docker push $MusicImage
