name: Docker Image CI

on:
  push:
    branches: [ "final" ]
  pull_request:
    branches: [ "final" ]
env:
  TEST_TAG: qiugu/music:2.0

jobs:
  build:
    name: Build base image and project image
    runs-on: ubuntu-latest
    env:
      BaseImage: qiugu/dep:2.0
      MusicImage: qiugu/music:1.0
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t $MusicImage --cache-from $BaseImage --cache-from $MusicImage .
  push:
    needs: build
    name: Log in and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: qiugu/music

      - name: Test
        run: |
          cd /tmp
          ls -al
          # docker run --rm ${{ env.TEST_TAG }}
      
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/dockerfile/react-music-player/Dockerfile
          load: true
          tags: ${{ env.TEST_TAG }} 

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
